// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oifbdvjigknnzgxfpznh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pZmJkdmppZ2tubnpneGZwem5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NjY5NjcsImV4cCI6MjA2ODU0Mjk2N30.0TSDrgXME1uwactPV3uGWu0Zdq-lcZHTRT93xwC0SNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});